<link href="{{ public_path('/others/stisla_admin_v1.0.0/dist/modules/bootstrap/css/bootstrap.min.css') }}" rel="stylesheet">
<link href="{{ public_path('/others/stisla_admin_v1.0.0/dist/css/domPDF.css') }}" rel="stylesheet">
<style>
    thead { display: table-header-group }
        tfoot { display: table-row-group }
        tr { page-break-inside: avoid }
    footer { 
        position: fixed; 
        bottom:100px; 
        left: 0px; 
        right: 0px;
        height: -50px; 
    }
    .marginTop{
        margin-top:6rem!important;
    }
    .marginTable{
        margin-top:16rem!important;
    } 
    .textLine{
        width: 80%;
        margin: auto;
        margin-top: 5%;
        margin-bottom: 5%;
        border-color: black;
    }
    </style>
<body>
    <div class="row">
        <div class="col-6 float-left">
            <h4 class="text-center mb-2">Tugmaster Bargepool Inc</h4>
            <h6 class="text-center mb-2">404 San Fernando St., Binondo, Metro Manila</h6>
            <h6 class="text-center mb-4">Tel Nos. 710-59-80 / 925-91-81</h6>
            <div class="mb-1 font-weight-bold">
                Towed by :
            </div>
            <div class="mb-1">
                Captain :
            </div>
            <div class="mb-1">
                Chief Engineer :
            </div>
        </div>
        <div class="col-6 float-right">
            <h5 class="text-center font-weight-bold mb-5">DISPATCH TICKET</h5>
            <div class="mb-1 marginTop">
                Date :
            </div>
            <div class="mb-1">
                Craft Towed :
            </div>
            <div class="mb-1">
                Account of :
            </div>
        </div>
    </div>
    <footer class="text-center">Generated by TSMS</footer>
    <div class="marginTable">
        <table class="text-center table table-striped border-primary">
            <thead class="bg-primary">
                <tr>
                    <th class="text-white">FROM</th>
                    <th class="text-white">TO</th>
                    <th class="text-white">TIME OUT</th>
                    <th class="text-white">TIME ARRIVED</th>
                    <th class="text-white">NATURE OR PURPOSE OF SERVICE</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td id="dispatch2">Pandacan</td>
                    <td id="tugboat">Manila</td>
                    <td id="start">23:50</td>
                    <td id="destination">11:40</td>
                    <td id="service">Hauling</td>
                </tr>
                <tr>
                    <td id="dispatch2">Pandacan</td>
                    <td id="tugboat">Manila</td>
                    <td id="start">23:50</td>
                    <td id="destination">11:40</td>
                    <td id="service">Hauling</td>
                </tr>
                <tr>
                    <td id="dispatch2">Pandacan</td>
                    <td id="tugboat">Manila</td>
                    <td id="start">23:50</td>
                    <td id="destination">11:40</td>
                    <td id="service">Hauling</td>
                </tr>
                <tr>
                    <td id="dispatch2">Pandacan</td>
                    <td id="tugboat">Manila</td>
                    <td id="start">23:50</td>
                    <td id="destination">11:40</td>
                    <td id="service">Hauling</td>
                </tr>
                <tr>
                    <td id="dispatch2">Pandacan</td>
                    <td id="tugboat">Manila</td>
                    <td id="start">23:50</td>
                    <td id="destination">11:40</td>
                    <td id="service">Hauling</td>
                </tr>
            </tbody>
        </table>
        <small class="mb-1">This is to certify that the foregoing facts are true and correct to the best of my knowledge and belief.</small>
    </div>
    <div class="row">
        <div class="col-6 float-left">
            <div class="mb-1 font-weight-bold">
                Total Days(s) hours:
            </div>
            <div style="margin-top:5rem!important;">
                <hr class="textLine">
                <p class="text-center">Captain's Signature </p>
            </div>
        </div>
        <div class="col-6 float-right">
            <h5 class="text-center font-weight-bold mb-5">CERTIFIED CORRECT BY: </h5>
            <div style="margin-top:5rem!important;">
                <hr class="textLine">
                <p class="text-center">Authorized Representative</p>
            </div>
        </div>
    </div>
</body>
        